name: knights_gambit
description: chess puzzle trainer
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  chess: ^0.8.1
  simple_chess_board: ^1.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/puzzles/chapter1_easy_puzzles.json
    - assets/puzzles/chapter2_intermediate_puzzles.json
    - assets/puzzles/chapter3_advanced_puzzles.json
    - assets/puzzles/endgame_trainer_endings_cleaned.json
    - assets/puzzles/endgame_trainer/
    - assets/images/logo.png
